version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: ./environments/local/Dockerfile
    container_name: gourmet-map-discord
    ports:
      - "3000:3000"
    volumes:
      - ../../data:/app/data
      - ../../src:/app/src
      - ../../public:/app/public
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - PORT=3000
    restart: unless-stopped
    # 開発時にホットリロードを有効にする場合はコメント解除
    # command: npm run dev
